server:
  port: 8083
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/zoffy_oauth
    username: postgres
    password: 1qaw3@123
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

keycloak:
  server:
    contextPath: /auth
    adminUser:
      username: zoffy
      password: m78m78
    realmImportFile: zoffy-realm.json